### ISSUE TITLE
Angle i ships är till synes onödigt, ta bort?

### ISSUE THREAD

**Issue by velixo** [voidcase/RadarSpadar#1]
@voidcase 

Märkte också att Ship.burn() existerar, onödig?

**Comment by velixo** [comment]
@voidcase

**Comment by voidcase** [comment]
Agreed.

**Comment by velixo** [comment]
Fixat i och med 80a5eddac6e1a2e947de249a05882f8f28038b42

**Comment by velixo** [comment]
Fixat i och med 80a5eddac6e1a2e947de249a05882f8f28038b42
